# Generated by Django 6.0.1 on 2026-02-18 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название')),
                ('author', models.CharField(max_length=100, verbose_name='Автор')),
                ('published_date', models.DateField(verbose_name='Дата первой публикации')),
                ('genre', models.CharField(max_length=50, verbose_name='Жанр')),
                ('language', models.CharField(max_length=50, verbose_name='Язык')),
                ('pages', models.PositiveIntegerField(verbose_name='Страницы')),
                ('description', models.TextField(verbose_name='Описание')),
                ('rating', models.FloatField(verbose_name='Оценка')),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='book_covers/')),
            ],
        ),
    ]
