# Generated by Django 6.0.1 on 2026-02-19 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='published_date',
            field=models.PositiveIntegerField(verbose_name='Год публикации'),
        ),
    ]
