# Generated by Django 6.0.1 on 2026-02-19 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_book_pdf_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='status',
            field=models.CharField(choices=[('regular', 'Обычная'), ('new', 'Новинка'), ('recommended', 'Рекомендуем'), ('best', 'Лучшие')], db_index=True, default='regular', max_length=20, verbose_name='Статус'),
        ),
    ]
